
# SEO settings
title: "In Was f√ºr einer Welt..."
title2: "" # default: ""
description: "Gedanken zu technischen und politischen Dingen...und manchmal auch Gott und die Welt."
keywords: ""
url: http://inwasfuereinerwelt.de # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/ronin1384/ronin1384.github.io
disqus_shortname: ""
twitter_username: ""
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Michael Hermeth"
  job      : ""
  bio      : ""
  thumb    : /images/author.jpg
  email    : info@inwasfuereinerwelt.de
  url      : http://mhermeth.de
  # github   : http://github.com/ronin1384
  # twitter  : http://twitter.com/HeiswayiNrird
  # facebook : https://www.facebook.com/heiswayi.nrird
  # linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "de_DE"
# twitter_card: "summary_large_image"
# twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : impress
    title: Impressum
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
